### PR TITLE
Fix supplier command

### LINKED ISSUE #80: Add "-s" prefix to supplier commands
Abstract out supplier prefix ("-s") and delivery prefix ("-d")
Update AddressBookParser to reflect the use of appropriate prefixes
Update mark supplier command
Update tests to reflect the new use of supplier prefix

### PR DESCRIPTION
**Pull request by ngjianyi**
Fixes #80

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/CliSyntax.java [hunk 1]
```diff
@@ -13,8 +15,9 @@ public class CliSyntax {
     public static final Prefix PREFIX_COMPANY = new Prefix("com/");
     public static final Prefix PREFIX_TAG = new Prefix("t/");
     public static final Prefix PREFIX_PRODUCT = new Prefix("pro/");
+    public static final Prefix PREFIX_SUPPLIER_STATUS = new Prefix("s/");
```
Comment (LinkesV) [inline src/main/java/seedu/address/logic/parser/CliSyntax.java:18]: what is this prefix used for?

**Review by LinkesV — APPROVED** [review]
LGTM
