### PR TITLE
Fix bugs in FindDeliveryCommand and MarkDeliveryCommand

### LINKED ISSUE #138: Delivery can be marked with status that is identical to current status
For instance when delivery is currently delivered, it can be marked as delivered again

### LINKED ISSUE #139: Mark delivery success message misleading
Currently when marking a delivery that has status as cancelled to delivered, the printed out message is 
"Marked Delivery: John Doe; Date & time: 18-06-2024 17:00; Product: bread; Quantity: 500 g; Cost: 25.50; 
Status: CANCELLED as DELIVERED"

The message can be misleading as it can be viewed as current status of delivery is "CANCELLED as DELIVERED"

### LINKED ISSUE #140: Find delivery usage message missing "-d"
The command usage message displayed currently is "find on/23-08-2024 20:21 stat/DELIVERED pro/iPhone"

### PR DESCRIPTION
**Pull request by prave1n**
Fixes #138
Fixes #139
Fixes #140

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -32,6 +32,7 @@ public class Messages {
             + "list    : Lists both suppliers and deliveries (No parameters should be given)\n"
             + "list -d : Lists deliveries to the user\n"
             + "list -s : Lists suppliers to the user";
+    public static final String MESSAGE_DELIVERY_ALREADY_HAS_STATUS = "%1$s is already marked as %2$s";
```
Comment (CJianzhi) [inline src/main/java/seedu/address/logic/Messages.java:35]: Should this be named DELIVERY_ALREADY_HAS_STATUS_MESSAGE instead?

**Review by CJianzhi — APPROVED** [review]
LGTM! Updated changes fix currently specified bugs!
