### PR TITLE
Fix Alpha Bugs assigned to me

### LINKED ISSUE #133: Add delivery command to shorten 'liters' in quantity field
Add delivery command currently requires litres to be labelled as 'liters' in the quantity
This could be changed to 'l' as a short form and be consistent with the other units

### LINKED ISSUE #147: Changing units for quantity when adding deliveries still counts as duplicate delivery
After adding a delivery with quantity "500 kg", keeping all other fields the same, it is not possible to add another delivery with quantity "500g" as it is recognised as a duplicate delivery.

### LINKED ISSUE #148: Add supplier command result display bug in Products
Screenshot 2024-11-05 at 5 18 06 PM

Bug with the result display with regards to Product. We are missing a semicolon : and there needs to be spacing between the different products.

### LINKED ISSUE #153: Add delivery error message
Screenshot 2024-11-05 at 5 55 48 PM

It should indicate that a space is needed between the value and unit

### LINKED ISSUE #154: Disparity between find commands for supplier and delivery with respect to products
Find command for supplier and delivery for products varies. For deliveries it must be exact and for supplier it can "contain" the keyword only. 

We need to standardise this issue

### LINKED ISSUE #155: Remane of name predicate for Supplier Find Command
Rename the predicate and remove the unused predicate for the Find Command

### LINKED ISSUE #161: Change the USERGUIDE_URL
It is in the HELPWINDOW.java

### PR DESCRIPTION
**Pull request by LinkesV**
Fixes #161 
Fixes #155 
Fixes #154 
Fixes #153 
Fixes #148 
Fixes #147 
Fixes #133

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
 import java.util.Set;
 import java.util.stream.Stream;
 
-import seedu.address.logic.commands.AddCommand;
+import seedu.address.logic.commands.AddSupplierCommand;
```
Comment (prave1n) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:14]: Since AddCommand was renamed to AddSupplier command, should this parser be renamed to AddSupplierCommandParser?

File: src/test/java/seedu/address/model/supplier/predicate/NameContainsPredicateTest.java [hunk 2]
```diff
@@ -6,21 +6,21 @@
 
 import org.junit.jupiter.api.Test;
 
-import seedu.address.model.supplier.predicates.NameContainsPredicate;
+import seedu.address.model.supplier.predicates.NameContainsKeywordPredicate;
```
Comment (prave1n) [inline src/test/java/seedu/address/model/supplier/predicate/NameContainsPredicateTest.java:9]: Should this test file be renamed to NameContainsKeywordPredicateTest.java

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 3]
```diff
@@ -42,7 +42,7 @@
 import org.junit.jupiter.api.Test;
 
 import seedu.address.logic.Messages;
-import seedu.address.logic.commands.AddCommand;
+import seedu.address.logic.commands.AddSupplierCommand;
```
Comment (prave1n) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:45]: Should this be renamed to AddSupplierCommandParserTest?

File: src/test/java/seedu/address/logic/commands/AddCommandTest.java [hunk 4]
```diff
@@ -31,43 +31,43 @@ public class AddCommandTest {
 
     @Test
     public void constructor_nullSupplier_throwsNullPointerException() {
-        assertThrows(NullPointerException.class, () -> new AddCommand(null));
+        assertThrows(NullPointerException.class, () -> new AddSupplierCommand(null));
```
Comment (prave1n) [inline src/test/java/seedu/address/logic/commands/AddCommandTest.java:34]: Should this file be renamed to AddSupplierCommandTest?

**Review by prave1n — APPROVED** [review]
LGTM, just want to highlight some naming issues for the AddSupplierCommand and its associated classes like the parser and test files.
