### PR TITLE
Fix bugs in Add Delivery and Upcoming Command

### LINKED ISSUE #129: Change message for Upcoming command

### LINKED ISSUE #133: Add delivery command to shorten 'liters' in quantity field
Add delivery command currently requires litres to be labelled as 'liters' in the quantity
This could be changed to 'l' as a short form and be consistent with the other units

### LINKED ISSUE #153: Add delivery error message
Screenshot 2024-11-05 at 5 55 48 PM

It should indicate that a space is needed between the value and unit

### PR DESCRIPTION
**Pull request by CJianzhi**
Change upcoming command message to remove the optional keyword
Change Quantity for products from litres to l
Change constraint message for Quantity of AddDeliveryCommand

fixes #153 
fixes #129
fixes #133

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java [hunk 1]
```diff
@@ -32,7 +32,7 @@ public class AddDeliveryCommand extends Command {
             + PREFIX_DATETIME + "dd-mm-yyyy hh:mm "
             + PREFIX_SUPPLIER_INDEX + "SUPPLIER_INDEX "
             + PREFIX_PRODUCT + "PRODUCT "
-            + PREFIX_QUANTITY + "QUANTITY kg/g/litres/ml/units "
+            + PREFIX_QUANTITY + "QUANTITY kg/g/l/ml/units "
```
Comment (LinkesV) [inline src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java:35]: I think litre should be represented by L and millilitre should be represented by mL

**Review by LinkesV — APPROVED** [review]
LGTM. Just minot changes for the quanity redux
