### PR TITLE
Fix bug in FindDelivery command after sorting suppliers

### LINKED ISSUE #183: Find delivery by supplier index after sorting suppliers does not find deliveries by the correct supplier

### PR DESCRIPTION
**Pull request by prave1n**
Fixes #183

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public CommandResult execute(Model model) {
 
         // If supplier index is provided, retrieve the supplier and filter by that supplier
         if (supplierIndex.isPresent()) {
-            List<Supplier> lastShownList = model.getFilteredSupplierList();
+            List<Supplier> lastShownList = model.getModifiedSupplierList();
```
Comment (LinkesV) [inline src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java:62]: Nice catch. We should do one more round of check to ensure getModifiedSupplierList is used properly

**Review by LinkesV — APPROVED** [review]
LGTM
